#!/usr/bin/env bash
# GPU queue worker — sequential Boltz-2 batches across 5 cached-MSA targets.
# Each batch: top100 novel BRICS candidates × 1 target = ~25 min GPU.
# Total: 5 × 25min = ~2h. Runs until all done.

set -uo pipefail
cd /home/crazat/genesis_medicine
source .venv/bin/activate

OUT=pilot/gpu_queue
mkdir -p $OUT

log() { echo "[$(date +%H:%M:%S)] $1"; }

# 5 anti-fibrotic / pigmentation / alopecia targets with cached MSAs
declare -A TARGETS=(
    [ctgf]="MTAASMGPVRVAFVVLLALCSRPAVGQNCSGPCRCPDEPAPRCPAGVSLVLDGCGCCRVCAKQLGELCTERDPCDPHKGLFCDFGSPANRKIGVCTAKDGAPCIFGGTVYRSGESFQSSCKYQCTCLDGAVGCMPLCSMDVRLPSPDCPFPRRVKLPGKCCEEWVCDEPKDQTVVGPALAAYRLEDTFGPDPTMIRANCLVQTTEWSACSKTCGMGISTRVTNDNASCRLEKQSRLCMVRPCEADLEENIKKGKKCIRTPKISKPIKFELSGCTSMKTYRAKFCGVCTDGRCCTPHRTTTLPVEFKCPDGEVMKKNMMFIKTCACHYNCPGDNDIFESLYYRKMYGDMA"
    [sirt1]="MADEAALALQPGGSPSAAGADREAASSPAGEPLRKRPRRDGPGLERSPGEPGGAAPEREVPAAARGCPGAAAAALWREAEAEAAAAGGEQEAHATESHPESLSHPEPRTPAPSGCQRAAQDVRTPPDAEMPEPAEKQELSGEPCKVPGAEGSSLDPVMSLELLRRLAGPVPLEKAEYQLLEQQVRHPELQGKRSAEEPYDFLLGLAVKLNPALPKFGKPVCGREMRWGEPLGSPHELLRAVERMVKVPSEIDIAAKLKNNKEGGKLLEDSEELL"
    [lox]="MRFLLLPLLLPLLLPLLPSPRLPRSAPHGPDPAEEVLLHAAGCRGCRAATKAKDLREELLAGKHFRLEIPLREAVPETSCSPLVRDLAFLPNHTLPRKEEFAKHRALETSKKHHSNGTAKKEYREAKDPCDLPTERVEDSAKPNFLEYDEFRYHTDSNADGRAALDAYHSEEHHLAVPFGEGAERDESEHFRRGFKERSPGSQGRGYHAEGYNNCDGFTSRYEDLNPLELASCKEMKKTVEYDQRFLLELRERSGRDFADHLDFKEKNLLKHEAEGELQ"
    [ar]="MEVQLGLGRVYPRPPSKTYRGAFQNLFQSVREVIQNPGPRHPEAASAAPPGASLLLLQQQQQQQQQQQQQQQQQQQQQQQETSPRQQQQQQGEDGSPQAHRRGPTGYLVLDEEQQPSQPQSALECHPERGCVPEPGAAVAASKGLPQQLPAPPDEDDSAAPSTLSLLGPTFPGLSSCSADLKDILSEASTMQLLQQQQQEAVSEGSSSGRAREASGAPTSSKDNYLGGTSTISDNAKELCKAVSVSMGLGVEALEHLSPGEQLRGDCMYAPLLGVPPAVRPTPCAPLAECKGSLLDDSAGKSTEDTAEYSPFKGGYTKGLEGESLGCSGSAAAGSSGTLELPSTLSLYKSGALDEAAAYQSRDYYNFPLALAGPPPPPPPPHPHARIKLENPLDYGSAWAAAAAQCRYGDLASLHGAGAAGPGSGSPSAAASSSWHTLFTAEEGQLYGPCGGGGGGGGGGGGGGGGGGGGGGGGGGEAGAVAPYGYTRPPQGLAGQESDFTAPDVWYPGGMVSRVPYPSPTCVKSEMGPWMDSYSGPYGDMRLETARDHVLPIDYYFPPQKTCLICGDEASGCHYGALTCGSCKVFFKRAAEGKQKYLCASRNDCTIDKFRRKNCPSCRLRKCYEAGMTLGARKLKKLGNLKLQEEGEASSTTSPTEETTQKLTVSHIEGYECQPIFLNVLEAIEPGVVCAGHDNNQPDSFAALLSSLNELGERQLVHVVKWAKALPGFRNLHVDDQMAVIQYSWMGLMVFAMGWRSFTNVNSRMLYFAPDLVFNEYRMHKSRMYSQCVRMRHLSQEFGWLQITPQEFLCMKALLLFSIIPVDGLKNQKFFDELRMNYIKELDRIIACKRKNPTSCSRRFYQLTKLLDSVQPIARELHQFTFDLLIKSHMVSVDFPEMMAEIISVQVPKILSGKVKPIYFHTQ"
    [mitf]="MLEMLEYNHYQVQTHLENPTKYHIQQAQRQQVKQYLSTTLANKHANQVLSLPCPNQPGDHVMPPVPGSSAPNSPMAMLTLNSNCEKEGFYKFEEQNRAESECPGMNTHSRASCMQMDDVIDDIISLESSYNEEILGLMDPALQMANTLPVSGNLIDLYGNQGLPPPGLTISNSCPANLPNIKRELTACIFPGEDHENLCNHFSDLYEQTSREIIQDIANPKFTSLKPADCATKAKLDLCAYGGPNGCVCDTFLHKYNNPLMQFIVDTEDASDLNYICPFCGTGFKPGGNLASHRVRKHNGGFHRFRPNMITGEKNSKCIYCGMTKLSGPELISHIRRFHKDMPNGTYKSCKRKTYILTEGISEDKDFPLCNGRDDPDADAPGFAEEKNPQKCSSALESQREN"
)

ITER=0
for target in ctgf sirt1 lox ar mitf; do
    ITER=$((ITER+1))
    log "=== GPU batch $ITER/5: top100 × $target ==="

    # Generate yamls
    INPUT_DIR=pilot/gpu_queue/inputs_${target}
    mkdir -p $INPUT_DIR
    rm -f $INPUT_DIR/*.yaml

    python -c "
import pandas as pd, yaml
from pathlib import Path
df = pd.read_csv('pilot/cpu_queue_v5/top100_novel_candidates.csv')
seq = '''${TARGETS[$target]}'''
seq = ''.join(seq.split())
msa_path = '/home/crazat/genesis_medicine/data/msa/${target}.a3m'
out = Path('${INPUT_DIR}')
for i, r in df.reset_index(drop=True).iterrows():
    yaml_data = {
        'version': 1,
        'sequences': [
            {'protein': {'id':'A', 'sequence': seq, 'msa': msa_path}},
            {'ligand': {'id':'B', 'smiles': r['smiles']}},
        ],
        'properties': [{'affinity': {'binder': 'B'}}],
    }
    (out / f'${target}__top{i:03d}.yaml').write_text(yaml.safe_dump(yaml_data, sort_keys=False))
print(f'  ${target}: {len(df)} yamls')
"

    log "  Boltz-2 inference starting..."
    boltz predict $INPUT_DIR \
        --out_dir pilot/gpu_queue/output_${target} \
        --sampling_steps 25 --diffusion_samples 1 --recycling_steps 3 \
        --sampling_steps_affinity 200 --diffusion_samples_affinity 5 \
        --affinity_mw_correction --devices 1 \
        > pilot/gpu_queue/log_${target}.log 2>&1
    log "  ✅ $target done"
done

log "=== All 5 GPU batches DONE ==="
