"""Prep Boltz-2 yamls for low-coverage targets (SRD5A2, JUN, PTGS2, DCT) ×
top100 BRICS so the next GPU chain step can fill gaps."""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import yaml

ROOT = Path(__file__).resolve().parents[1]


TARGETS = {
    "srd5a2": "MQVQCQQSPVLAGSATLVALGALALYVAKPSGYGKHTESLKPAATRLPARAAWFLQELPSFLLPLAILAQLPLLLPGTLVPRADGAVTQLLAGFTLVHTLNLPLAALCSAVRLLPRMQGGRRSPGAFAVPYLPVKAGRYHARTYAFFTLAVLAAGSGFVQAAYLDQYIRDPSAPLPLATATALATSEQSLEFNTAFAITNRYRRTPVNFKKILELELQDFRVKPATELHWLTAYTDPLPRMVHHCHEFGVQLDEVLLEDFGLAGLSPVTDVRSGTGSYAVKFRGTGLPDFLAGFLNRGSEEYRVLAEQQGNLAYGNQHTYLEYDDRLLR",
    "ptgs2": "MLARALLLCAVLALSHTANPCCSHPCQNRGVCMSVGFDQYKCDCTRTGFYGENCSTPEFLTRIKLFLKPTPNTVHYILTHFKGFWNVVNNIPFLRNAIMSYVLTSRSHLIDSPPTYNADYGYKSWEAFSNLSYYTRALPPVPDDCPTPLGVKGKKQLPDSNEIVEKLLLRRKFIPDPQGSNMMFAFFAQHFTHQFFKTDHKRGPAFTNGLGHGVDLNHIYGETLARQRKLRLFKDGKMKYQIIDGEMYPPTVKDTQAEMIYPPQVPEHLRFAVGQEVFGLVPGLMMYATIWLREHNRVCDVLKQEHPEWGDEQLFQTSRLILIGETIKIVIEDYVQHLSGYHFKLKFDPELLFNKQFQYQNRIAAEFNTLYHWHPLLPDTFQIHDQKYNYQQFIYNNSILLEHGITQFVESFTRQIAGRVAGGRNVPPAVQKVSQASIDQSRQMKYQSFNEYRKRFMLKPYESFEELTGEKEMSAELEALYGDIDAVELYPALLVEKPRPDAIFGETMVEVGAPFSLKGLMGNVICSPAYWKPSTFGGEVGFQIINTASIQSLICNNVKGCPFTSFSVPDPELIKTVTINASSSRSGLDDINPTVLLKERSTEL",
    "jun": "MTAKMETTFYDDALNASFLPSESGPYGYSNPKILKQSMTLNLADPVGSLKPHLRAKNSDLLTSPDVGLLKLASPELERLIIQSSNGHITTTPTPTQFLCPKNVTDEQEGFAEGFVRALAELHSQNTLPSVTSAAQPVNGAGMVAPAVASVAGGSGSGGFSASLHSEPPVYANLSNFNPGALSSGGGAPSYGAAGLAFPAQPQQQQQPPHHLPQQMPVQHPRLQALKEEPQTVPEMPGETPPLSPIDMESQERIKAERKRMRNRIAASKCRKRKLERIARLEEKVKTLKAQNSELASTANMLREQVAQLKQKVMNHVNSGCQLMLTQQLQTF",
    "dct": "MSPLWWGFLLSCLGCKILPGAQGQFPRVCMTVDSLVNKECCPRLGAESANVCGSQQGRGQCTEVRADTRPWSGPYILRNQDDRELWPRKFFHRTCKCTGNFAGYNCGDCKFGWTGPNCERKKPPVIRQNIHSLSPQERELFLGAFADYGAGSRNPSDPMLAPTSRLGYLYGAEDLRTSLAEEMHSLAQAVLPRFFFHKYGRKHAERIQKLRDIYVSALRHWGQAVRLEHENCEEVDELSWDQLDFFRCVSGMLELDRSCQLPSDSMLLEFTPDVPKVQFCSAVSQARKLQDNSLPCVVCGKHKVNPCVGCRNRTPDLFAYNTSCPSLHLPRFFPCSCALEPYRGRYTLAAKILREDLGSYRRLEISFGQGYEKWAGSEDPRACGRCDR",
}


def main():
    df = pd.read_csv(ROOT / "pilot/cpu_queue_v5/top100_novel_candidates.csv")
    print(f"Top 100 BRICS: {len(df)}")
    for tname, tseq in TARGETS.items():
        out_dir = ROOT / f"pilot/cpu_meaningful/inputs_{tname}"
        out_dir.mkdir(parents=True, exist_ok=True)
        msa_path = ROOT / f"data/msa/{tname}.a3m"
        msa_param = str(msa_path) if msa_path.exists() else None
        seq = "".join(tseq.split())

        n = 0
        for i, r in df.head(100).reset_index(drop=True).iterrows():
            protein_block = {"id": "A", "sequence": seq}
            if msa_param:
                protein_block["msa"] = msa_param
            yaml_data = {
                "version": 1,
                "sequences": [
                    {"protein": protein_block},
                    {"ligand": {"id": "B", "smiles": r["smiles"]}},
                ],
                "properties": [{"affinity": {"binder": "B"}}],
            }
            (out_dir / f"{tname}__top{i:03d}.yaml").write_text(
                yaml.safe_dump(yaml_data, sort_keys=False)
            )
            n += 1
        print(f"  {tname}: {n} yamls (msa cached={msa_param is not None})")


if __name__ == "__main__":
    sys.exit(main())
